### ISSUE TITLE
1 Flaw

### ISSUE THREAD

**Issue by Gtrstv** [schedutron/python-algo-trading#1]
I reviewed this code, and have more of an accounting Issue than a coding 1. I used the code from your original medium article.
I was able to reproduce those results. I then pulled the Nasdaq stock ticker index and ran this with a maximum investment of 75000 and spending of 30000. I only ran for 10 years as I was iterating over 3500 tickers for North America. I got the same impressive results but at a smaller scale. almost 500%. The issue I have is that the Dow or any other market indicator has been rising for the past 20 years. I got an identical timeline copy of the DOW and charted both. They mirror each other. The issue I see is this return could backfire in a bear market. a good example would be the drop in prices in march of 2020 when covid19 hit. Your algorithm should be picking the best stocks, but its not over that period. All in all, it's a great piece of coding. 

![charts](https://user-images.githubusercontent.com/71386993/108761467-e5363080-751c-11eb-8813-f3d78b0ce9b3.jpg)

**Comment by schedutron** [comment]
Just noticed this now, thanks for highlighting this, @Gtrstv
Thinking of a naive improvement - maybe just have a check to detect the inflection point where a bear run is anticipated to last for a while - then maybe sell early and buy something like SPXS (the 3x leveraged S&P 500 fund) - simpler than resorting to direct shorts :)

**Comment by Gtrstv** [comment]
First off, if you implemented this with real money after you wrote the article, Congratulations. Your now in a higher tax bracket. As far as the market corrections, even now with the economy slowly recovering, the market reaction to economic indicators is not proportional to the actual event. The Fed can’t raise interests rates a quarter of a percent without causing stock prices to plummet. I believe that high frequency trading is causing the trend. In any event, I noticed that there is a high negative correlation between the economic recovery and tech stocks. Also, many market segments are negatively correlated. If you segmented your portfolio, you could maximize return without having to leave the market entirely, but you would probably want to review some market crash data, so you can know when to get out of every position and go to a money market fund. You would need to add a field to the tickers to show segments then get overall segment returns. Also, I think the fact that your code is set for every two weeks works well as it doesnt follow common indicators like the 5, 100, 200 day moving average that are stock points for institutional investors. Good Luck, I havent had a chance to do further work on finance lately, but I hope to get to that soon, then I can try a few ideas with small purchases.

**Comment by michaels429** [comment]
Thank you for work you've done.  I downloaded your code and tried to run it using Python 3.10.  I previously downloaded the adjusted closes and volumes using yfinance and stored that data in their respective files. In any event, the code kept crashing because of the date. 

So I installed Python 3.7 and at least got it to run but with no real results. I keep getting a $1000000 as the result for all dates.  When I look at the results of around line 86 (see below)

series = volumechanges.loc[start_date:today].mean()

The series shows each stock symbol accompanied with a Nan.   Plus I get nothing in the "interestlst".  Therefore, no buys nor sells.

Would you be willing to help me figure why this doesn't work?
Thanks,
Mike S
michaels429@outlook.com
